import type { Plugin } from "vue";
import { GlobalAnimateConfig } from "./common/config";
// 导入指令
import { bounceDirective } from "./directives/bounce";
import { flashDirective } from "./directives/flash";
import { pulseDirective } from "./directives/pulse";
import { rubberBandDirective } from "./directives/rubber-band";
import { shakeXDirective } from "./directives/shake-x";
import { shakeYDirective } from "./directives/shake-y";
import { headShakeDirective } from "./directives/head-shake";
import { swingDirective } from "./directives/swing";
import { tadaDirective } from "./directives/tada";
import { wobbleDirective } from "./directives/wobble";
import { jelloDirective } from "./directives/jello";
import { heartBeatDirective } from "./directives/heart-beat";
import { backInDownDirective } from "./directives/back-in-down";
import { backInLeftDirective } from "./directives/back-in-left";
import { backInRightDirective } from "./directives/back-in-right";
import { backInUpDirective } from "./directives/back-in-up";
import { backOutDownDirective } from "./directives/back-out-down";
import { backOutLeftDirective } from "./directives/back-out-left";
import { backOutRightDirective } from "./directives/back-out-right";
import { backOutUpDirective } from "./directives/back-out-up";
import { bounceInDirective } from "./directives/bounce-in";
import { bounceInDownDirective } from "./directives/bounce-in-down";
import { bounceInLeftDirective } from "./directives/bounce-in-left";
import { bounceInRightDirective } from "./directives/bounce-in-right";
import { bounceInUpDirective } from "./directives/bounce-in-up";
import { bounceOutDirective } from "./directives/bounce-out";
import { bounceOutDownDirective } from "./directives/bounce-out-down";
import { bounceOutLeftDirective } from "./directives/bounce-out-left";
import { bounceOutRightDirective } from "./directives/bounce-out-right";
import { bounceOutUpDirective } from "./directives/bounce-out-up";
import { fadeInDirective } from "./directives/fade-in";
import { fadeInDownDirective } from "./directives/fade-in-down";
import { fadeInDownBigDirective } from "./directives/fade-in-down-big";
import { fadeInLeftDirective } from "./directives/fade-in-left";
import { fadeInLeftBigDirective } from "./directives/fade-in-left-big";
import { fadeInRightDirective } from "./directives/fade-in-right";
import { fadeInRightBigDirective } from "./directives/fade-in-right-big";
import { fadeInUpDirective } from "./directives/fade-in-up";
import { fadeInUpBigDirective } from "./directives/fade-in-up-big";
import { fadeInTopLeftDirective } from "./directives/fade-in-top-left";
import { fadeInTopRightDirective } from "./directives/fade-in-top-right";
import { fadeInBottomLeftDirective } from "./directives/fade-in-bottom-left";
import { fadeInBottomRightDirective } from "./directives/fade-in-bottom-right";
import { fadeOutDirective } from "./directives/fade-out";
import { fadeOutDownDirective } from "./directives/fade-out-down";
import { fadeOutDownBigDirective } from "./directives/fade-out-down-big";
import { fadeOutLeftDirective } from "./directives/fade-out-left";
import { fadeOutLeftBigDirective } from "./directives/fade-out-left-big";
import { fadeOutRightDirective } from "./directives/fade-out-right";
import { fadeOutRightBigDirective } from "./directives/fade-out-right-big";
import { fadeOutUpDirective } from "./directives/fade-out-up";
import { fadeOutUpBigDirective } from "./directives/fade-out-up-big";
import { fadeOutTopLeftDirective } from "./directives/fade-out-top-left";
import { fadeOutTopRightDirective } from "./directives/fade-out-top-right";
import { fadeOutBottomRightDirective } from "./directives/fade-out-bottom-right";
import { fadeOutBottomLeftDirective } from "./directives/fade-out-bottom-left";
import { flipDirective } from "./directives/flip";
import { flipInXDirective } from "./directives/flip-in-x";
import { flipInYDirective } from "./directives/flip-in-y";
import { flipOutXDirective } from "./directives/flip-out-x";
import { flipOutYDirective } from "./directives/flip-out-y";
import { lightSpeedInRightDirective } from "./directives/light-speed-in-right";
import { lightSpeedInLeftDirective } from "./directives/light-speed-in-left";
import { lightSpeedOutRightDirective } from "./directives/light-speed-out-right";
import { lightSpeedOutLeftDirective } from "./directives/light-speed-out-left";
import { rotateInDirective } from "./directives/rotate-in";
import { rotateInDownLeftDirective } from "./directives/rotate-in-down-left";
import { rotateInDownRightDirective } from "./directives/rotate-in-down-right";
import { rotateInUpLeftDirective } from "./directives/rotate-in-up-left";
import { rotateInUpRightDirective } from "./directives/rotate-in-up-right";
import { rotateOutDirective } from "./directives/rotate-out";
import { rotateOutDownLeftDirective } from "./directives/rotate-out-down-left";
import { rotateOutDownRightDirective } from "./directives/rotate-out-down-right";
import { rotateOutUpLeftDirective } from "./directives/rotate-out-up-left";
import { rotateOutUpRightDirective } from "./directives/rotate-out-up-right";
import { hingeDirective } from "./directives/hinge";
import { jackInTheBoxDirective } from "./directives/jack-in-the-box";
import { rollInDirective } from "./directives/roll-in";
import { rollOutDirective } from "./directives/roll-out";
import { zoomInDirective } from "./directives/zoom-in";
import { zoomInDownDirective } from "./directives/zoom-in-down";
import { zoomInLeftDirective } from "./directives/zoom-in-left";
import { zoomInRightDirective } from "./directives/zoom-in-right";
import { zoomInUpDirective } from "./directives/zoom-in-up";
import { zoomOutDirective } from "./directives/zoom-out";
import { zoomOutDownDirective } from "./directives/zoom-out-down";
import { zoomOutLeftDirective } from "./directives/zoom-out-left";
import { zoomOutRightDirective } from "./directives/zoom-out-right";
import { zoomOutUpDirective } from "./directives/zoom-out-up";
import { slideInDownDirective } from "./directives/slide-in-down";
import { slideInLeftDirective } from "./directives/slide-in-left";
import { slideInRightDirective } from "./directives/slide-in-right";
import { slideInUpDirective } from "./directives/slide-in-up";
import { slideOutDownDirective } from "./directives/slide-out-down";
import { slideOutLeftDirective } from "./directives/slide-out-left";
import { slideOutRightDirective } from "./directives/slide-out-right";
import { slideOutUpDirective } from "./directives/slide-out-up";

export const vueAnimateCss = (config?: GlobalAnimateConfig): Plugin => ({
  install(app) {
    config?.initConfig();
    // 注册指令
    bounceDirective.install!(app);
    flashDirective.install!(app);
    pulseDirective.install!(app);
    rubberBandDirective.install!(app);
    shakeXDirective.install!(app);
    shakeYDirective.install!(app);
    headShakeDirective.install!(app);
    swingDirective.install!(app);
    tadaDirective.install!(app);
    wobbleDirective.install!(app);
    jelloDirective.install!(app);
    heartBeatDirective.install!(app);
    backInDownDirective.install!(app);
    backInLeftDirective.install!(app);
    backInRightDirective.install!(app);
    backInUpDirective.install!(app);
    backOutDownDirective.install!(app);
    backOutLeftDirective.install!(app);
    backOutRightDirective.install!(app);
    backOutUpDirective.install!(app);
    bounceInDirective.install!(app);
    bounceInDownDirective.install!(app);
    bounceInLeftDirective.install!(app);
    bounceInRightDirective.install!(app);
    bounceInUpDirective.install!(app);
    bounceOutDirective.install!(app);
    bounceOutDownDirective.install!(app);
    bounceOutLeftDirective.install!(app);
    bounceOutRightDirective.install!(app);
    bounceOutUpDirective.install!(app);
    fadeInDirective.install!(app);
    fadeInDownDirective.install!(app);
    fadeInDownBigDirective.install!(app);
    fadeInLeftDirective.install!(app);
    fadeInLeftBigDirective.install!(app);
    fadeInRightDirective.install!(app);
    fadeInRightBigDirective.install!(app);
    fadeInUpDirective.install!(app);
    fadeInUpBigDirective.install!(app);
    fadeInTopLeftDirective.install!(app);
    fadeInTopRightDirective.install!(app);
    fadeInBottomLeftDirective.install!(app);
    fadeInBottomRightDirective.install!(app);
    fadeOutDirective.install!(app);
    fadeOutDownDirective.install!(app);
    fadeOutDownBigDirective.install!(app);
    fadeOutLeftDirective.install!(app);
    fadeOutLeftBigDirective.install!(app);
    fadeOutRightDirective.install!(app);
    fadeOutRightBigDirective.install!(app);
    fadeOutUpDirective.install!(app);
    fadeOutUpBigDirective.install!(app);
    fadeOutTopLeftDirective.install!(app);
    fadeOutTopRightDirective.install!(app);
    fadeOutBottomRightDirective.install!(app);
    fadeOutBottomLeftDirective.install!(app);
    flipDirective.install!(app);
    flipInXDirective.install!(app);
    flipInYDirective.install!(app);
    flipOutXDirective.install!(app);
    flipOutYDirective.install!(app);
    lightSpeedInRightDirective.install!(app);
    lightSpeedInLeftDirective.install!(app);
    lightSpeedOutRightDirective.install!(app);
    lightSpeedOutLeftDirective.install!(app);
    rotateInDirective.install!(app);
    rotateInDownLeftDirective.install!(app);
    rotateInDownRightDirective.install!(app);
    rotateInUpLeftDirective.install!(app);
    rotateInUpRightDirective.install!(app);
    rotateOutDirective.install!(app);
    rotateOutDownLeftDirective.install!(app);
    rotateOutDownRightDirective.install!(app);
    rotateOutUpLeftDirective.install!(app);
    rotateOutUpRightDirective.install!(app);
    hingeDirective.install!(app);
    jackInTheBoxDirective.install!(app);
    rollInDirective.install!(app);
    rollOutDirective.install!(app);
    zoomInDirective.install!(app);
    zoomInDownDirective.install!(app);
    zoomInLeftDirective.install!(app);
    zoomInRightDirective.install!(app);
    zoomInUpDirective.install!(app);
    zoomOutDirective.install!(app);
    zoomOutDownDirective.install!(app);
    zoomOutLeftDirective.install!(app);
    zoomOutRightDirective.install!(app);
    zoomOutUpDirective.install!(app);
    slideInDownDirective.install!(app);
    slideInLeftDirective.install!(app);
    slideInRightDirective.install!(app);
    slideInUpDirective.install!(app);
    slideOutDownDirective.install!(app);
    slideOutLeftDirective.install!(app);
    slideOutRightDirective.install!(app);
    slideOutUpDirective.install!(app);
  }
});
